#!/usr/bin/env python3
#
# Regenerate src/tdma_field/font_unscii8.c: an 8x8 CFB font for the field
# variant's 128x64 OLED.
#
# Why: the fonts CFB bundles (CONFIG_CHARACTER_FRAMEBUFFER_USE_DEFAULT_FONTS)
# are 10x16, 15x24 and 20x32. The smallest gives 12 columns x 4 rows on
# 128x64, too few for the live soak screen. CFB only renders fonts whose
# height is a multiple of 8, so 8 px is the only smaller height, and an 8x8
# cell gives 16 x 8.
#
# Source: LVGL's lv_font_unscii_8.c from the NCS workspace. LVGL generated it
# from unscii-8 (Viznut, public domain) with lv_font_conv at 1 bpp. That
# format stores each glyph as a cropped box, row-major, MSB-first bits packed
# across rows. CFB wants a full cell stored column by column
# (CFB_FONT_MONO_VPACKED, LSB = top row, one byte per column at 8 px high).
# This script re-places each box in its 8x8 cell and repacks it. It is a
# mechanical conversion; no glyph is edited by hand.
#
# Usage:
#   python gen_font_unscii8.py <lv_font_unscii_8.c> <out.c>
# e.g.
#   python src/tdma_field/tools/gen_font_unscii8.py \
#       C:/ncs/v3.2.0/modules/lib/gui/lvgl/src/font/lv_font_unscii_8.c \
#       src/tdma_field/font_unscii8.c
#
# SPDX-License-Identifier: Apache-2.0

import re
import sys

CELL = 8
FIRST = 32
LAST = 126  # CFB's own fonts stop at '~'; DEL is not printable


def parse(path):
    src = open(path, encoding="utf-8").read()

    m = re.search(r"glyph_bitmap\[\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        sys.exit("glyph_bitmap not found")
    body = re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S)
    bitmap = [int(v, 16) for v in re.findall(r"0x[0-9a-fA-F]+", body)]

    dsc = []
    for d in re.finditer(
            r"\.bitmap_index\s*=\s*(\d+),\s*\.adv_w\s*=\s*(\d+),\s*"
            r"\.box_w\s*=\s*(\d+),\s*\.box_h\s*=\s*(\d+),\s*"
            r"\.ofs_x\s*=\s*(-?\d+),\s*\.ofs_y\s*=\s*(-?\d+)", src):
        dsc.append(tuple(int(x) for x in d.groups()))

    m = re.search(r"\.range_start\s*=\s*(\d+),\s*\.range_length\s*=\s*(\d+),"
                  r"\s*\.glyph_id_start\s*=\s*(\d+)", src)
    if not m:
        sys.exit("cmap not found")
    start, length, gid0 = (int(x) for x in m.groups())
    if "FORMAT0_TINY" not in src or "bpp = 1" not in src:
        sys.exit("expected a 1 bpp font with one contiguous FORMAT0_TINY cmap")
    return bitmap, dsc, start, length, gid0


def glyph_cell(bitmap, d):
    """Return an 8x8 [row][col] pixel grid for one glyph descriptor."""
    idx, adv_w, bw, bh, ox, oy = d
    if adv_w != CELL * 16:
        sys.exit(f"not monospaced at {CELL} px (adv_w={adv_w})")
    cell = [[0] * CELL for _ in range(CELL)]
    # base_line is 0, so ofs_y is the box's bottom edge above the cell's
    # bottom row.
    top = CELL - oy - bh
    bit = 0
    for r in range(bh):
        for c in range(bw):
            byte = bitmap[idx + bit // 8]
            on = (byte >> (7 - bit % 8)) & 1
            bit += 1
            if not on:
                continue
            y, x = top + r, ox + c
            if not (0 <= y < CELL and 0 <= x < CELL):
                sys.exit(f"lit pixel outside the {CELL}x{CELL} cell")
            cell[y][x] = 1
    return cell


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_font_unscii8.py <lv_font_unscii_8.c> <out.c>")
    bitmap, dsc, start, length, gid0 = parse(sys.argv[1])

    out = []
    out.append("""/*
 * 8x8 CFB font for the field variant's 128x64 OLED: 16 columns x 8 rows.
 *
 * GENERATED by tools/gen_font_unscii8.py. Do not edit by hand; rerun the
 * script instead.
 *
 * Glyphs: unscii-8 by Viznut (public domain), taken from the conversion
 * shipped in LVGL (lv_font_unscii_8.c, MIT, Copyright (c) LVGL Kft) and
 * repacked for CFB: CFB_FONT_MONO_VPACKED, one byte per column, LSB = top row.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/kernel.h>

#if defined(CONFIG_APP_TDMA_FIELD)

#include <zephyr/display/cfb.h>
""")
    out.append(f"static const uint8_t font_unscii8_data[{LAST - FIRST + 1}][{CELL}] = {{")
    for ch in range(FIRST, LAST + 1):
        if not (start <= ch < start + length):
            sys.exit(f"char {ch} not in the source font")
        cell = glyph_cell(bitmap, dsc[gid0 + ch - start])
        cols = []
        for x in range(CELL):
            v = 0
            for y in range(CELL):
                v |= cell[y][x] << y
            cols.append(v)
        label = chr(ch).replace("\\", "backslash").replace("*/", "* /")
        out.append(f"\t/* {ch} '{label}' */")
        out.append("\t{ " + ", ".join(f"0x{v:02x}" for v in cols) + " },")
        for y in range(CELL):
            row = "".join("#" if cell[y][x] else "." for x in range(CELL))
            out.append(f"\t/*   {row} */")
    out.append("};")
    out.append("")
    out.append(f"FONT_ENTRY_DEFINE(font_unscii8, {CELL}, {CELL}, "
               f"CFB_FONT_MONO_VPACKED, font_unscii8_data, {FIRST}, {LAST});")
    out.append("")
    out.append("#endif /* CONFIG_APP_TDMA_FIELD */")
    out.append("")

    with open(sys.argv[2], "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
